import { Check, X, Copy, Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";

const finalOutput = `# Functional Requirements: User Authentication Flow

## FR-001: OAuth2 Authentication
| ID | Requirement |
|---|---|
| FR-001.1 | The system SHALL provide OAuth2 authentication via Google provider |
| FR-001.2 | The system SHALL provide OAuth2 authentication via GitHub provider |
| FR-001.3 | The system SHALL display an error message if the OAuth provider is unavailable |
| FR-001.4 | The system SHALL implement PKCE flow for enhanced security |

## FR-002: Session Management
| ID | Requirement |
|---|---|
| FR-002.1 | The system SHALL persist user sessions across browser tabs |
| FR-002.2 | The system SHALL store authentication tokens in httpOnly cookies |
| FR-002.3 | The system SHALL implement automatic token refresh before expiration |

## FR-003: Logout Functionality
| ID | Requirement |
|---|---|
| FR-003.1 | The system SHALL provide a logout button in the navigation |
| FR-003.2 | Upon logout, the system SHALL invalidate all session tokens |
| FR-003.3 | Upon logout, the system SHALL clear all client-side session data |
| FR-003.4 | Upon logout, the system SHALL redirect the user to the login page |

## FR-004: Post-Authentication Redirect
| ID | Requirement |
|---|---|
| FR-004.1 | After successful authentication, the system SHALL redirect the user to the dashboard |
| FR-004.2 | The system SHALL preserve the originally requested URL for post-login redirect |

---
*Generated by SpecSmith AI • Issue #102 • January 15, 2024*`;

export function OutputPanel() {
  const { toast } = useToast();

  const handleCopy = () => {
    navigator.clipboard.writeText(finalOutput);
    toast({
      title: "Copied to clipboard",
      description: "Requirements have been copied to your clipboard.",
    });
  };

  const handleApprove = () => {
    toast({
      title: "Requirements Approved",
      description: "The requirements have been marked as approved and will be pushed to GitLab.",
    });
  };

  const handleReject = () => {
    toast({
      title: "Requirements Rejected",
      description: "The requirements have been sent back to the agents for revision.",
      variant: "destructive",
    });
  };

  return (
    <div className="h-full flex flex-col">
      <div className="flex items-center justify-between p-4 border-b border-border">
        <h3 className="font-semibold text-sm">Final Requirements</h3>
        <div className="flex items-center gap-1">
          <Button
            variant="ghost"
            size="sm"
            onClick={handleCopy}
            className="h-7 text-xs gap-1.5"
          >
            <Copy className="w-3 h-3" />
          </Button>
          <Button
            variant="ghost"
            size="sm"
            className="h-7 text-xs gap-1.5"
          >
            <Download className="w-3 h-3" />
          </Button>
        </div>
      </div>

      <div className="flex-1 overflow-auto p-4">
        <div className="p-4 rounded-lg bg-muted/30 border border-border font-mono text-xs whitespace-pre-wrap leading-relaxed">
          {finalOutput}
        </div>
      </div>

      <div className="p-4 border-t border-border flex gap-3">
        <Button
          onClick={handleApprove}
          className="flex-1 gradient-success text-success-foreground"
        >
          <Check className="w-4 h-4 mr-2" />
          Approve
        </Button>
        <Button
          onClick={handleReject}
          variant="outline"
          className="flex-1 border-destructive/30 text-destructive hover:bg-destructive/10"
        >
          <X className="w-4 h-4 mr-2" />
          Reject
        </Button>
      </div>
    </div>
  );
}
